### ISSUE TITLE
请问有兴趣参与中文编程的讨论吗?

### ISSUE THREAD

**Issue by nobodxbodon** [nicemorning007/CHN#1]
很高兴看到你的实践. 刚新建的[github中文编程讨论组](https://github.com/program-in-chinese/overview/issues), 希望汇聚各种背景的对中文编写代码感兴趣的开发者. 欢迎光临!

**Comment by nicemorning007** [comment]
抱歉由于最近设备问题。今天才登陆了邮箱。这个讨论抱歉不能参加了



发自我的小米手机
在 Xuan Wu <notifications@github.com>，2017年10月20日 04:32写道：

讨论组里正在进行C/C++编译器汉化相关的讨论, 包括关键词用词等. 有兴趣欢迎一起探讨.

**Comment by nobodxbodon** [comment]
No problem.
Thanks for replying.
